// This file is generated by Slice Machine. Update with care!

import LinkCard from './LinkCard';
import Text from './Text';

export {
	LinkCard,
	Text,
};

export const components = {
	link_card: LinkCard,
	text: Text,
};
